### PR TITLE
Make the grid's xcolor and ycolor parameters optional

### LINKED ISSUE #5: Fix NAND Getting Started Example Error
I'm trying to run the NAND example from the [getting started instructions](https://laygo2.github.io/examples_link.html#simple-gate-generation).  However, when I run it I get an error suggesting the 'xcolor' and 'ycolor' parameters need to be defined in the example technology.  Can you help fix this example?

## Error

Note: I moved the "examples/" directory into "laygo2/examples/" so I can use importlib.resources.files to get the tech_params filepath easily

```bash
/space/mayberc/envs/mambaforge/envs/laygo2-dev/bin/python /prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/simple_gates/nand_generate.py
Load templates
<laygo2.object.template.UserDefinedTemplate object at 0x7efdc7b43e20> name: pmos, class: UserDefinedTemplate, 
<laygo2.object.template.UserDefinedTemplate object at 0x7efdc7b43e50> name: nmos, class: UserDefinedTemplate, 
Load grids
Traceback (most recent call last):
  File "/prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/simple_gates/nand_generate.py", line 55, in <module>
    grids = tech.load_grids(templates=templates)
  File "/prj/ids_dev/work_libs/mayberc/laygo2/laygo2/examples/technology_example/technology_example_grids.py", line 50, in load_grids
    g = laygo2.object.grid.RoutingGrid(name=gname, vgrid=gv, hgrid=gh,
TypeError: __init__() missing 2 required positional arguments: 'xcolor' and 'ycolor'
```

## Problematic code
xcolor and ycolor should be passed in.  I assume they should also be in the tech_params yaml file.

Starting at line 50 of technology_example_grids.py:

``` python
g = laygo2.object.grid.RoutingGrid(name=gname, vgrid=gv, hgrid=gh,
                                               vwidth=vwidth, hwidth=hwidth,
                                               vextension=vextension, hextension=hextension,
                                               vlayer=vlayer, hlayer=hlayer,
                                               pin_vlayer=pin_vlayer, pin_hlayer=pin_hlayer,
                                               viamap=viamap, primary_grid=primary_grid)
```

### PR DESCRIPTION
**Pull request by curtisma**
I made the xcolor/ycolor arguments in RoutingGrid optional parameters for the grid class, as they are not required in planar MPT.

Fixes #5

### CODE REVIEW

**Comment by jdhan** [comment]
I think we need to add a list composed of 'not MPT' if xcolor is not received as follows?

'
  ycolor = list()
        if 'ycolor' in grid['horizontal'].keys():
            if grid['horizontal']['ycolor'] == 'not MPT':
                ycolor = np.array(['not MPT']*hlayer.shape[0], dtype=object)
            else:
                ycolor.append( grid['horizontal']['ycolor'])
        else:
            **ycolor = np.array(['not MPT']*hlayer.shape[0], dtype=object)**
'

**Comment by jdhan** [comment]
nvm I'll just merge the request and add the not MPT stuff by myself.

**Comment by curtisma** [comment]
Ok, thanks, but why did you decide to set it to "not mpt" instead of None?  

If you were to add the appropriate type hint Optional[List[str]] that would correspond to using None when not provided.

It seems a little confusing to get "not mpt" when people expect it to be a color.  None seems a little more clear that there is no color.   Could there also be other reasons why there is no color provided even when it is mpt?

**Comment by jdhan** [comment]
I totally agree with you that 'not MPT' is the best way of describing the mono-color grids. None would be easier to understand/handle but I don't want to change the notation at this moment just because some of the students in my group working on a tapeout in this month is using that notation. I don't want to break their flow. Perhaps we can review related code and change the notation after the tapeout.

In any case, thanks for your valuable comment on this.

**Pull request merged**
